name: Lint

on:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - README.md
      - .gitignore
  pull_request_target:
    branches:
      - main
      - dev
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install npm dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Lint commit message
        run: echo "$CI_COMMIT_MESSAGE" | npx commitlint